
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftplusminuslefttimesdivisionand bool division double_equal equal float greater greater_equal id int l_bra l_cbra l_par less less_equal minus mod not not_equal or plus power r_bra r_cbra r_par string timesinit  :  instruction_listinstruction_list : int plus int'
    
_lr_action_items = {'int':([0,4,],[3,5,]),'$end':([1,2,5,],[0,-1,-2,]),'plus':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instruction_list':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instruction_list','init',1,'p_init','grammar.py',126),
  ('instruction_list -> int plus int','instruction_list',3,'p_instruction_list','grammar.py',130),
]
